name: Run Pytest on Commit
on: [ push ]

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      checks: write
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'
          architecture: 'x64'
      - run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest-bdd
      - name: Run Pytest and Generate JUnit Report
        run: pytest --junitxml=pytest-results.xml
      - name: Upload Test Results
        uses: actions/upload-artifact@v3
        if: success() || failure() # always run even if the previous step fails
        with:
          name: pytest-results
          path: pytest-results.xml
      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v4
        if: success() || failure() # always run even if the previous step fails
        with:
          report_paths: 'pytest-results.xml'
